version: '3.8'

services:
  #  database
  postgres:
    image: postgres:latest
    container_name: task-service_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: task-service_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - zipkin-network

  #   database for keycloak
  postgres-keycloak:
    image: postgres:latest
    container_name: keycloak_dbs
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_keycloak_data:/var/lib/postgresql/data

  #   Keycloak container
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak_con
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak_db
      - DB_USER=keycloak
      - DB_PASSWORD=keycloakpass
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    command: start-dev
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - postgres-keycloak
    networks:
      - zipkin-network

  # Zipkin for tracing with PostgreSQL
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin_cont
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    networks:
      - zipkin-network

volumes:
  postgres_data:
  postgres_keycloak_data:

networks:
  zipkin-network:
    driver: bridge
