spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://localhost:5432/task_service_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Mini-project002
          jwk-set-uri: http://localhost:8080/realms/Mini-project002/protocol/openid-connect/certs
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
openapi:
  service:
    title: task-service doc
    version: 1.0.0
    url: http://localhost:8081
springdoc:
  api-docs:
    path: /task-service/v3/api-docs
  swagger-ui:
    path: /task-service/swagger-ui.html
    oauth:
      client-id: mini-project
      client-secret: xF6dq9UAZXi4gOpe27K0cwG4EjKFRYYg
server:
  port: 8086
