spring:
  application:
    name: task-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
openapi:
  service:
    title: task-service doc
    version: 1.0.0
    url: http://localhost:8081

springdoc:
  api-docs:
    path: /task-service/api/v1/api-docs
  swagger-ui:
    path: /task-service/swagger-ui.html
server:
  port: 8081